on:
  push:
    branches: ["main"]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint:check
  Test:
    runs-on: ${{ matrix.os }}
    needs: [Lint]
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x, 16.x, 17.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-python@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-cdk${{ hashFiles('package-lock.json') }}

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test
        env:
          CI: true
          EXCHANGE_OMS_ID: 1
          ISOLATE: true

  Deploy:
    runs-on: ubuntu-latest
    needs: [Lint, Test]

    steps:
      - name: Cache Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-cdk${{ hashFiles('package-lock.json') }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Runtime
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org/bundless-core"

      - name: Install
        run: |
          npm install

      - name: Deploy
        run: |
          npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
