on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x, 16.x, 17.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-python@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cdk${{ hashFiles('package.json') }}

      - name: Install
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint:check

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test
